package zebedee

const (
	PageTypeAPIDataset                string = "api_dataset"
	PageTypeAPIDatasetLandingPage     string = "api_dataset_landing_page"
	PageTypeArticle                   string = "article"
	PageTypeArticleDownload           string = "article_download"
	PageTypeBulletin                  string = "bulletin"
	PageTypeChart                     string = "chart"
	PageTypeCompendiumChapter         string = "compendium_chapter"
	PageTypeCompendiumData            string = "compendium_data"
	PageTypeCompendiumLandingPage     string = "compendium_landing_page"
	PageTypeDataset                   string = "dataset"
	PageTypeDatasetLandingPage        string = "dataset_landing_page"
	PageTypeDataSlice                 string = "data_slice"
	PageTypeEquation                  string = "equation"
	PageTypeHomePage                  string = "home_page"
	PageTypeHomePageCensus            string = "home_page_census"
	PageTypeImage                     string = "image"
	PageTypeProductPage               string = "product_page"
	PageTypeReferenceTables           string = "reference_tables"
	PageTypeRelease                   string = "release"
	PageTypeStaticAdhoc               string = "static_adhoc"
	PageTypeStaticArticle             string = "static_article"
	PageTypeStaticFOI                 string = "static_foi"
	PageTypeStaticLandingPage         string = "static_landing_page"
	PageTypeStaticMethodology         string = "static_methodology"
	PageTypeStaticMethodologyDownload string = "static_methodology_download"
	PageTypeStaticPage                string = "static_page"
	PageTypeStaticQMI                 string = "static_qmi"
	PageTypeTable                     string = "table"
	PageTypeTaxonomyLanding           string = "taxonomy_landing_page"
	PageTypeTimeseries                string = "timeseries"
	PageTypeTimeseriesDataset         string = "timeseries_dataset"
	PageTypeTimeseriesLandingPage     string = "timeseries_landing_page"
	PageTypeVisualisation             string = "visualisation"
)
