// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/zebedee"
	health "github.com/ONSdigital/dp-healthcheck/healthcheck"
	"io"
	"net/http"
	"sync"
)

// Ensure, that ClienterMock does implement zebedee.Clienter.
// If this is not the case, regenerate this file with moq.
var _ zebedee.Clienter = &ClienterMock{}

// ClienterMock is a mock implementation of zebedee.Clienter.
//
//	func TestSomethingThatUsesClienter(t *testing.T) {
//
//		// make and configure a mocked zebedee.Clienter
//		mockedClienter := &ClienterMock{
//			ApproveCollectionFunc: func(ctx context.Context, authToken string, collectionID string) error {
//				panic("mock out the ApproveCollection method")
//			},
//			ApproveCollectionContentFunc: func(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error {
//				panic("mock out the ApproveCollectionContent method")
//			},
//			CheckCollectionsForURIFunc: func(ctx context.Context, authToken string, uri string) (string, bool, error) {
//				panic("mock out the CheckCollectionsForURI method")
//			},
//			CheckerFunc: func(ctx context.Context, check *health.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			CompleteCollectionContentFunc: func(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error {
//				panic("mock out the CompleteCollectionContent method")
//			},
//			CreateCollectionFunc: func(ctx context.Context, authToken string, collection zebedee.Collection) (zebedee.Collection, error) {
//				panic("mock out the CreateCollection method")
//			},
//			DeleteCollectionFunc: func(ctx context.Context, authToken string, collectionID string) error {
//				panic("mock out the DeleteCollection method")
//			},
//			DeleteCollectionContentFunc: func(ctx context.Context, authToken string, collectionID string, pagePath string) error {
//				panic("mock out the DeleteCollectionContent method")
//			},
//			GetFunc: func(ctx context.Context, authToken string, path string) ([]byte, error) {
//				panic("mock out the Get method")
//			},
//			GetBreadcrumbFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) ([]zebedee.Breadcrumb, error) {
//				panic("mock out the GetBreadcrumb method")
//			},
//			GetBulletinFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Bulletin, error) {
//				panic("mock out the GetBulletin method")
//			},
//			GetCollectionFunc: func(ctx context.Context, authToken string, collectionID string) (zebedee.Collection, error) {
//				panic("mock out the GetCollection method")
//			},
//			GetDatasetFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Dataset, error) {
//				panic("mock out the GetDataset method")
//			},
//			GetDatasetLandingPageFunc: func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error) {
//				panic("mock out the GetDatasetLandingPage method")
//			},
//			GetFileSizeFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error) {
//				panic("mock out the GetFileSize method")
//			},
//			GetHomepageContentFunc: func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.HomepageContent, error) {
//				panic("mock out the GetHomepageContent method")
//			},
//			GetPageDataFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageData, error) {
//				panic("mock out the GetPageData method")
//			},
//			GetPageDescriptionFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageDescription, error) {
//				panic("mock out the GetPageDescription method")
//			},
//			GetPageTitleFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageTitle, error) {
//				panic("mock out the GetPageTitle method")
//			},
//			GetPublishedDataFunc: func(ctx context.Context, uriString string) ([]byte, error) {
//				panic("mock out the GetPublishedData method")
//			},
//			GetPublishedIndexFunc: func(ctx context.Context, params *zebedee.PublishedIndexRequestParams) (zebedee.PublishedIndex, error) {
//				panic("mock out the GetPublishedIndex method")
//			},
//			GetReleaseFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Release, error) {
//				panic("mock out the GetRelease method")
//			},
//			GetResourceBodyFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) ([]byte, error) {
//				panic("mock out the GetResourceBody method")
//			},
//			GetResourceStreamFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (io.ReadCloser, error) {
//				panic("mock out the GetResourceStream method")
//			},
//			GetTimeseriesMainFigureFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.TimeseriesMainFigure, error) {
//				panic("mock out the GetTimeseriesMainFigure method")
//			},
//			GetWithHeadersFunc: func(ctx context.Context, authToken string, path string) ([]byte, http.Header, error) {
//				panic("mock out the GetWithHeaders method")
//			},
//			PostFunc: func(ctx context.Context, authToken string, path string, payload []byte) ([]byte, http.Header, error) {
//				panic("mock out the Post method")
//			},
//			PublishCollectionFunc: func(ctx context.Context, authToken string, collectionID string) error {
//				panic("mock out the PublishCollection method")
//			},
//			PutFunc: func(ctx context.Context, authToken string, path string, payload []byte) (*http.Response, error) {
//				panic("mock out the Put method")
//			},
//			PutDatasetInCollectionFunc: func(ctx context.Context, authToken string, collectionID string, lang string, datasetID string, state string) error {
//				panic("mock out the PutDatasetInCollection method")
//			},
//			PutDatasetVersionInCollectionFunc: func(ctx context.Context, authToken string, collectionID string, lang string, datasetID string, edition string, version string, state string) error {
//				panic("mock out the PutDatasetVersionInCollection method")
//			},
//			SaveContentToCollectionFunc: func(ctx context.Context, authToken string, collectionID string, pagePath string, content interface{}) error {
//				panic("mock out the SaveContentToCollection method")
//			},
//		}
//
//		// use mockedClienter in code that requires zebedee.Clienter
//		// and then make assertions.
//
//	}
type ClienterMock struct {
	// ApproveCollectionFunc mocks the ApproveCollection method.
	ApproveCollectionFunc func(ctx context.Context, authToken string, collectionID string) error

	// ApproveCollectionContentFunc mocks the ApproveCollectionContent method.
	ApproveCollectionContentFunc func(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error

	// CheckCollectionsForURIFunc mocks the CheckCollectionsForURI method.
	CheckCollectionsForURIFunc func(ctx context.Context, authToken string, uri string) (string, bool, error)

	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, check *health.CheckState) error

	// CompleteCollectionContentFunc mocks the CompleteCollectionContent method.
	CompleteCollectionContentFunc func(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error

	// CreateCollectionFunc mocks the CreateCollection method.
	CreateCollectionFunc func(ctx context.Context, authToken string, collection zebedee.Collection) (zebedee.Collection, error)

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(ctx context.Context, authToken string, collectionID string) error

	// DeleteCollectionContentFunc mocks the DeleteCollectionContent method.
	DeleteCollectionContentFunc func(ctx context.Context, authToken string, collectionID string, pagePath string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, authToken string, path string) ([]byte, error)

	// GetBreadcrumbFunc mocks the GetBreadcrumb method.
	GetBreadcrumbFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) ([]zebedee.Breadcrumb, error)

	// GetBulletinFunc mocks the GetBulletin method.
	GetBulletinFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Bulletin, error)

	// GetCollectionFunc mocks the GetCollection method.
	GetCollectionFunc func(ctx context.Context, authToken string, collectionID string) (zebedee.Collection, error)

	// GetDatasetFunc mocks the GetDataset method.
	GetDatasetFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Dataset, error)

	// GetDatasetLandingPageFunc mocks the GetDatasetLandingPage method.
	GetDatasetLandingPageFunc func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error)

	// GetFileSizeFunc mocks the GetFileSize method.
	GetFileSizeFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error)

	// GetHomepageContentFunc mocks the GetHomepageContent method.
	GetHomepageContentFunc func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.HomepageContent, error)

	// GetPageDataFunc mocks the GetPageData method.
	GetPageDataFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageData, error)

	// GetPageDescriptionFunc mocks the GetPageDescription method.
	GetPageDescriptionFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageDescription, error)

	// GetPageTitleFunc mocks the GetPageTitle method.
	GetPageTitleFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageTitle, error)

	// GetPublishedDataFunc mocks the GetPublishedData method.
	GetPublishedDataFunc func(ctx context.Context, uriString string) ([]byte, error)

	// GetPublishedIndexFunc mocks the GetPublishedIndex method.
	GetPublishedIndexFunc func(ctx context.Context, params *zebedee.PublishedIndexRequestParams) (zebedee.PublishedIndex, error)

	// GetReleaseFunc mocks the GetRelease method.
	GetReleaseFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Release, error)

	// GetResourceBodyFunc mocks the GetResourceBody method.
	GetResourceBodyFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) ([]byte, error)

	// GetResourceStreamFunc mocks the GetResourceStream method.
	GetResourceStreamFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (io.ReadCloser, error)

	// GetTimeseriesMainFigureFunc mocks the GetTimeseriesMainFigure method.
	GetTimeseriesMainFigureFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.TimeseriesMainFigure, error)

	// GetWithHeadersFunc mocks the GetWithHeaders method.
	GetWithHeadersFunc func(ctx context.Context, authToken string, path string) ([]byte, http.Header, error)

	// PostFunc mocks the Post method.
	PostFunc func(ctx context.Context, authToken string, path string, payload []byte) ([]byte, http.Header, error)

	// PublishCollectionFunc mocks the PublishCollection method.
	PublishCollectionFunc func(ctx context.Context, authToken string, collectionID string) error

	// PutFunc mocks the Put method.
	PutFunc func(ctx context.Context, authToken string, path string, payload []byte) (*http.Response, error)

	// PutDatasetInCollectionFunc mocks the PutDatasetInCollection method.
	PutDatasetInCollectionFunc func(ctx context.Context, authToken string, collectionID string, lang string, datasetID string, state string) error

	// PutDatasetVersionInCollectionFunc mocks the PutDatasetVersionInCollection method.
	PutDatasetVersionInCollectionFunc func(ctx context.Context, authToken string, collectionID string, lang string, datasetID string, edition string, version string, state string) error

	// SaveContentToCollectionFunc mocks the SaveContentToCollection method.
	SaveContentToCollectionFunc func(ctx context.Context, authToken string, collectionID string, pagePath string, content interface{}) error

	// calls tracks calls to the methods.
	calls struct {
		// ApproveCollection holds details about calls to the ApproveCollection method.
		ApproveCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
		}
		// ApproveCollectionContent holds details about calls to the ApproveCollectionContent method.
		ApproveCollectionContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// PagePath is the pagePath argument value.
			PagePath string
		}
		// CheckCollectionsForURI holds details about calls to the CheckCollectionsForURI method.
		CheckCollectionsForURI []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// URI is the uri argument value.
			URI string
		}
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Check is the check argument value.
			Check *health.CheckState
		}
		// CompleteCollectionContent holds details about calls to the CompleteCollectionContent method.
		CompleteCollectionContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// PagePath is the pagePath argument value.
			PagePath string
		}
		// CreateCollection holds details about calls to the CreateCollection method.
		CreateCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// Collection is the collection argument value.
			Collection zebedee.Collection
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
		}
		// DeleteCollectionContent holds details about calls to the DeleteCollectionContent method.
		DeleteCollectionContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// PagePath is the pagePath argument value.
			PagePath string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// Path is the path argument value.
			Path string
		}
		// GetBreadcrumb holds details about calls to the GetBreadcrumb method.
		GetBreadcrumb []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetBulletin holds details about calls to the GetBulletin method.
		GetBulletin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetCollection holds details about calls to the GetCollection method.
		GetCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
		}
		// GetDataset holds details about calls to the GetDataset method.
		GetDataset []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetDatasetLandingPage holds details about calls to the GetDatasetLandingPage method.
		GetDatasetLandingPage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// Path is the path argument value.
			Path string
		}
		// GetFileSize holds details about calls to the GetFileSize method.
		GetFileSize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetHomepageContent holds details about calls to the GetHomepageContent method.
		GetHomepageContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// Path is the path argument value.
			Path string
		}
		// GetPageData holds details about calls to the GetPageData method.
		GetPageData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetPageDescription holds details about calls to the GetPageDescription method.
		GetPageDescription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetPageTitle holds details about calls to the GetPageTitle method.
		GetPageTitle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetPublishedData holds details about calls to the GetPublishedData method.
		GetPublishedData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UriString is the uriString argument value.
			UriString string
		}
		// GetPublishedIndex holds details about calls to the GetPublishedIndex method.
		GetPublishedIndex []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *zebedee.PublishedIndexRequestParams
		}
		// GetRelease holds details about calls to the GetRelease method.
		GetRelease []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetResourceBody holds details about calls to the GetResourceBody method.
		GetResourceBody []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetResourceStream holds details about calls to the GetResourceStream method.
		GetResourceStream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetTimeseriesMainFigure holds details about calls to the GetTimeseriesMainFigure method.
		GetTimeseriesMainFigure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetWithHeaders holds details about calls to the GetWithHeaders method.
		GetWithHeaders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// Path is the path argument value.
			Path string
		}
		// Post holds details about calls to the Post method.
		Post []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// Path is the path argument value.
			Path string
			// Payload is the payload argument value.
			Payload []byte
		}
		// PublishCollection holds details about calls to the PublishCollection method.
		PublishCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// Path is the path argument value.
			Path string
			// Payload is the payload argument value.
			Payload []byte
		}
		// PutDatasetInCollection holds details about calls to the PutDatasetInCollection method.
		PutDatasetInCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// DatasetID is the datasetID argument value.
			DatasetID string
			// State is the state argument value.
			State string
		}
		// PutDatasetVersionInCollection holds details about calls to the PutDatasetVersionInCollection method.
		PutDatasetVersionInCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// DatasetID is the datasetID argument value.
			DatasetID string
			// Edition is the edition argument value.
			Edition string
			// Version is the version argument value.
			Version string
			// State is the state argument value.
			State string
		}
		// SaveContentToCollection holds details about calls to the SaveContentToCollection method.
		SaveContentToCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// PagePath is the pagePath argument value.
			PagePath string
			// Content is the content argument value.
			Content interface{}
		}
	}
	lockApproveCollection             sync.RWMutex
	lockApproveCollectionContent      sync.RWMutex
	lockCheckCollectionsForURI        sync.RWMutex
	lockChecker                       sync.RWMutex
	lockCompleteCollectionContent     sync.RWMutex
	lockCreateCollection              sync.RWMutex
	lockDeleteCollection              sync.RWMutex
	lockDeleteCollectionContent       sync.RWMutex
	lockGet                           sync.RWMutex
	lockGetBreadcrumb                 sync.RWMutex
	lockGetBulletin                   sync.RWMutex
	lockGetCollection                 sync.RWMutex
	lockGetDataset                    sync.RWMutex
	lockGetDatasetLandingPage         sync.RWMutex
	lockGetFileSize                   sync.RWMutex
	lockGetHomepageContent            sync.RWMutex
	lockGetPageData                   sync.RWMutex
	lockGetPageDescription            sync.RWMutex
	lockGetPageTitle                  sync.RWMutex
	lockGetPublishedData              sync.RWMutex
	lockGetPublishedIndex             sync.RWMutex
	lockGetRelease                    sync.RWMutex
	lockGetResourceBody               sync.RWMutex
	lockGetResourceStream             sync.RWMutex
	lockGetTimeseriesMainFigure       sync.RWMutex
	lockGetWithHeaders                sync.RWMutex
	lockPost                          sync.RWMutex
	lockPublishCollection             sync.RWMutex
	lockPut                           sync.RWMutex
	lockPutDatasetInCollection        sync.RWMutex
	lockPutDatasetVersionInCollection sync.RWMutex
	lockSaveContentToCollection       sync.RWMutex
}

// ApproveCollection calls ApproveCollectionFunc.
func (mock *ClienterMock) ApproveCollection(ctx context.Context, authToken string, collectionID string) error {
	if mock.ApproveCollectionFunc == nil {
		panic("ClienterMock.ApproveCollectionFunc: method is nil but Clienter.ApproveCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
	}
	mock.lockApproveCollection.Lock()
	mock.calls.ApproveCollection = append(mock.calls.ApproveCollection, callInfo)
	mock.lockApproveCollection.Unlock()
	return mock.ApproveCollectionFunc(ctx, authToken, collectionID)
}

// ApproveCollectionCalls gets all the calls that were made to ApproveCollection.
// Check the length with:
//
//	len(mockedClienter.ApproveCollectionCalls())
func (mock *ClienterMock) ApproveCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}
	mock.lockApproveCollection.RLock()
	calls = mock.calls.ApproveCollection
	mock.lockApproveCollection.RUnlock()
	return calls
}

// ApproveCollectionContent calls ApproveCollectionContentFunc.
func (mock *ClienterMock) ApproveCollectionContent(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error {
	if mock.ApproveCollectionContentFunc == nil {
		panic("ClienterMock.ApproveCollectionContentFunc: method is nil but Clienter.ApproveCollectionContent was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		PagePath     string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		PagePath:     pagePath,
	}
	mock.lockApproveCollectionContent.Lock()
	mock.calls.ApproveCollectionContent = append(mock.calls.ApproveCollectionContent, callInfo)
	mock.lockApproveCollectionContent.Unlock()
	return mock.ApproveCollectionContentFunc(ctx, authToken, collectionID, lang, pagePath)
}

// ApproveCollectionContentCalls gets all the calls that were made to ApproveCollectionContent.
// Check the length with:
//
//	len(mockedClienter.ApproveCollectionContentCalls())
func (mock *ClienterMock) ApproveCollectionContentCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	PagePath     string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		PagePath     string
	}
	mock.lockApproveCollectionContent.RLock()
	calls = mock.calls.ApproveCollectionContent
	mock.lockApproveCollectionContent.RUnlock()
	return calls
}

// CheckCollectionsForURI calls CheckCollectionsForURIFunc.
func (mock *ClienterMock) CheckCollectionsForURI(ctx context.Context, authToken string, uri string) (string, bool, error) {
	if mock.CheckCollectionsForURIFunc == nil {
		panic("ClienterMock.CheckCollectionsForURIFunc: method is nil but Clienter.CheckCollectionsForURI was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AuthToken string
		URI       string
	}{
		Ctx:       ctx,
		AuthToken: authToken,
		URI:       uri,
	}
	mock.lockCheckCollectionsForURI.Lock()
	mock.calls.CheckCollectionsForURI = append(mock.calls.CheckCollectionsForURI, callInfo)
	mock.lockCheckCollectionsForURI.Unlock()
	return mock.CheckCollectionsForURIFunc(ctx, authToken, uri)
}

// CheckCollectionsForURICalls gets all the calls that were made to CheckCollectionsForURI.
// Check the length with:
//
//	len(mockedClienter.CheckCollectionsForURICalls())
func (mock *ClienterMock) CheckCollectionsForURICalls() []struct {
	Ctx       context.Context
	AuthToken string
	URI       string
} {
	var calls []struct {
		Ctx       context.Context
		AuthToken string
		URI       string
	}
	mock.lockCheckCollectionsForURI.RLock()
	calls = mock.calls.CheckCollectionsForURI
	mock.lockCheckCollectionsForURI.RUnlock()
	return calls
}

// Checker calls CheckerFunc.
func (mock *ClienterMock) Checker(ctx context.Context, check *health.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ClienterMock.CheckerFunc: method is nil but Clienter.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Check *health.CheckState
	}{
		Ctx:   ctx,
		Check: check,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, check)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedClienter.CheckerCalls())
func (mock *ClienterMock) CheckerCalls() []struct {
	Ctx   context.Context
	Check *health.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		Check *health.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// CompleteCollectionContent calls CompleteCollectionContentFunc.
func (mock *ClienterMock) CompleteCollectionContent(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error {
	if mock.CompleteCollectionContentFunc == nil {
		panic("ClienterMock.CompleteCollectionContentFunc: method is nil but Clienter.CompleteCollectionContent was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		PagePath     string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		PagePath:     pagePath,
	}
	mock.lockCompleteCollectionContent.Lock()
	mock.calls.CompleteCollectionContent = append(mock.calls.CompleteCollectionContent, callInfo)
	mock.lockCompleteCollectionContent.Unlock()
	return mock.CompleteCollectionContentFunc(ctx, authToken, collectionID, lang, pagePath)
}

// CompleteCollectionContentCalls gets all the calls that were made to CompleteCollectionContent.
// Check the length with:
//
//	len(mockedClienter.CompleteCollectionContentCalls())
func (mock *ClienterMock) CompleteCollectionContentCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	PagePath     string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		PagePath     string
	}
	mock.lockCompleteCollectionContent.RLock()
	calls = mock.calls.CompleteCollectionContent
	mock.lockCompleteCollectionContent.RUnlock()
	return calls
}

// CreateCollection calls CreateCollectionFunc.
func (mock *ClienterMock) CreateCollection(ctx context.Context, authToken string, collection zebedee.Collection) (zebedee.Collection, error) {
	if mock.CreateCollectionFunc == nil {
		panic("ClienterMock.CreateCollectionFunc: method is nil but Clienter.CreateCollection was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		AuthToken  string
		Collection zebedee.Collection
	}{
		Ctx:        ctx,
		AuthToken:  authToken,
		Collection: collection,
	}
	mock.lockCreateCollection.Lock()
	mock.calls.CreateCollection = append(mock.calls.CreateCollection, callInfo)
	mock.lockCreateCollection.Unlock()
	return mock.CreateCollectionFunc(ctx, authToken, collection)
}

// CreateCollectionCalls gets all the calls that were made to CreateCollection.
// Check the length with:
//
//	len(mockedClienter.CreateCollectionCalls())
func (mock *ClienterMock) CreateCollectionCalls() []struct {
	Ctx        context.Context
	AuthToken  string
	Collection zebedee.Collection
} {
	var calls []struct {
		Ctx        context.Context
		AuthToken  string
		Collection zebedee.Collection
	}
	mock.lockCreateCollection.RLock()
	calls = mock.calls.CreateCollection
	mock.lockCreateCollection.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *ClienterMock) DeleteCollection(ctx context.Context, authToken string, collectionID string) error {
	if mock.DeleteCollectionFunc == nil {
		panic("ClienterMock.DeleteCollectionFunc: method is nil but Clienter.DeleteCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
	}
	mock.lockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	mock.lockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(ctx, authToken, collectionID)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//
//	len(mockedClienter.DeleteCollectionCalls())
func (mock *ClienterMock) DeleteCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}
	mock.lockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	mock.lockDeleteCollection.RUnlock()
	return calls
}

// DeleteCollectionContent calls DeleteCollectionContentFunc.
func (mock *ClienterMock) DeleteCollectionContent(ctx context.Context, authToken string, collectionID string, pagePath string) error {
	if mock.DeleteCollectionContentFunc == nil {
		panic("ClienterMock.DeleteCollectionContentFunc: method is nil but Clienter.DeleteCollectionContent was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		PagePath     string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		PagePath:     pagePath,
	}
	mock.lockDeleteCollectionContent.Lock()
	mock.calls.DeleteCollectionContent = append(mock.calls.DeleteCollectionContent, callInfo)
	mock.lockDeleteCollectionContent.Unlock()
	return mock.DeleteCollectionContentFunc(ctx, authToken, collectionID, pagePath)
}

// DeleteCollectionContentCalls gets all the calls that were made to DeleteCollectionContent.
// Check the length with:
//
//	len(mockedClienter.DeleteCollectionContentCalls())
func (mock *ClienterMock) DeleteCollectionContentCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	PagePath     string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		PagePath     string
	}
	mock.lockDeleteCollectionContent.RLock()
	calls = mock.calls.DeleteCollectionContent
	mock.lockDeleteCollectionContent.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ClienterMock) Get(ctx context.Context, authToken string, path string) ([]byte, error) {
	if mock.GetFunc == nil {
		panic("ClienterMock.GetFunc: method is nil but Clienter.Get was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AuthToken string
		Path      string
	}{
		Ctx:       ctx,
		AuthToken: authToken,
		Path:      path,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, authToken, path)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedClienter.GetCalls())
func (mock *ClienterMock) GetCalls() []struct {
	Ctx       context.Context
	AuthToken string
	Path      string
} {
	var calls []struct {
		Ctx       context.Context
		AuthToken string
		Path      string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetBreadcrumb calls GetBreadcrumbFunc.
func (mock *ClienterMock) GetBreadcrumb(ctx context.Context, authToken string, collectionID string, lang string, uri string) ([]zebedee.Breadcrumb, error) {
	if mock.GetBreadcrumbFunc == nil {
		panic("ClienterMock.GetBreadcrumbFunc: method is nil but Clienter.GetBreadcrumb was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetBreadcrumb.Lock()
	mock.calls.GetBreadcrumb = append(mock.calls.GetBreadcrumb, callInfo)
	mock.lockGetBreadcrumb.Unlock()
	return mock.GetBreadcrumbFunc(ctx, authToken, collectionID, lang, uri)
}

// GetBreadcrumbCalls gets all the calls that were made to GetBreadcrumb.
// Check the length with:
//
//	len(mockedClienter.GetBreadcrumbCalls())
func (mock *ClienterMock) GetBreadcrumbCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetBreadcrumb.RLock()
	calls = mock.calls.GetBreadcrumb
	mock.lockGetBreadcrumb.RUnlock()
	return calls
}

// GetBulletin calls GetBulletinFunc.
func (mock *ClienterMock) GetBulletin(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Bulletin, error) {
	if mock.GetBulletinFunc == nil {
		panic("ClienterMock.GetBulletinFunc: method is nil but Clienter.GetBulletin was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetBulletin.Lock()
	mock.calls.GetBulletin = append(mock.calls.GetBulletin, callInfo)
	mock.lockGetBulletin.Unlock()
	return mock.GetBulletinFunc(ctx, authToken, collectionID, lang, uri)
}

// GetBulletinCalls gets all the calls that were made to GetBulletin.
// Check the length with:
//
//	len(mockedClienter.GetBulletinCalls())
func (mock *ClienterMock) GetBulletinCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetBulletin.RLock()
	calls = mock.calls.GetBulletin
	mock.lockGetBulletin.RUnlock()
	return calls
}

// GetCollection calls GetCollectionFunc.
func (mock *ClienterMock) GetCollection(ctx context.Context, authToken string, collectionID string) (zebedee.Collection, error) {
	if mock.GetCollectionFunc == nil {
		panic("ClienterMock.GetCollectionFunc: method is nil but Clienter.GetCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
	}
	mock.lockGetCollection.Lock()
	mock.calls.GetCollection = append(mock.calls.GetCollection, callInfo)
	mock.lockGetCollection.Unlock()
	return mock.GetCollectionFunc(ctx, authToken, collectionID)
}

// GetCollectionCalls gets all the calls that were made to GetCollection.
// Check the length with:
//
//	len(mockedClienter.GetCollectionCalls())
func (mock *ClienterMock) GetCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}
	mock.lockGetCollection.RLock()
	calls = mock.calls.GetCollection
	mock.lockGetCollection.RUnlock()
	return calls
}

// GetDataset calls GetDatasetFunc.
func (mock *ClienterMock) GetDataset(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Dataset, error) {
	if mock.GetDatasetFunc == nil {
		panic("ClienterMock.GetDatasetFunc: method is nil but Clienter.GetDataset was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetDataset.Lock()
	mock.calls.GetDataset = append(mock.calls.GetDataset, callInfo)
	mock.lockGetDataset.Unlock()
	return mock.GetDatasetFunc(ctx, authToken, collectionID, lang, uri)
}

// GetDatasetCalls gets all the calls that were made to GetDataset.
// Check the length with:
//
//	len(mockedClienter.GetDatasetCalls())
func (mock *ClienterMock) GetDatasetCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetDataset.RLock()
	calls = mock.calls.GetDataset
	mock.lockGetDataset.RUnlock()
	return calls
}

// GetDatasetLandingPage calls GetDatasetLandingPageFunc.
func (mock *ClienterMock) GetDatasetLandingPage(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error) {
	if mock.GetDatasetLandingPageFunc == nil {
		panic("ClienterMock.GetDatasetLandingPageFunc: method is nil but Clienter.GetDatasetLandingPage was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		Path:         path,
	}
	mock.lockGetDatasetLandingPage.Lock()
	mock.calls.GetDatasetLandingPage = append(mock.calls.GetDatasetLandingPage, callInfo)
	mock.lockGetDatasetLandingPage.Unlock()
	return mock.GetDatasetLandingPageFunc(ctx, authToken, collectionID, lang, path)
}

// GetDatasetLandingPageCalls gets all the calls that were made to GetDatasetLandingPage.
// Check the length with:
//
//	len(mockedClienter.GetDatasetLandingPageCalls())
func (mock *ClienterMock) GetDatasetLandingPageCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	Path         string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}
	mock.lockGetDatasetLandingPage.RLock()
	calls = mock.calls.GetDatasetLandingPage
	mock.lockGetDatasetLandingPage.RUnlock()
	return calls
}

// GetFileSize calls GetFileSizeFunc.
func (mock *ClienterMock) GetFileSize(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error) {
	if mock.GetFileSizeFunc == nil {
		panic("ClienterMock.GetFileSizeFunc: method is nil but Clienter.GetFileSize was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetFileSize.Lock()
	mock.calls.GetFileSize = append(mock.calls.GetFileSize, callInfo)
	mock.lockGetFileSize.Unlock()
	return mock.GetFileSizeFunc(ctx, authToken, collectionID, lang, uri)
}

// GetFileSizeCalls gets all the calls that were made to GetFileSize.
// Check the length with:
//
//	len(mockedClienter.GetFileSizeCalls())
func (mock *ClienterMock) GetFileSizeCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetFileSize.RLock()
	calls = mock.calls.GetFileSize
	mock.lockGetFileSize.RUnlock()
	return calls
}

// GetHomepageContent calls GetHomepageContentFunc.
func (mock *ClienterMock) GetHomepageContent(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.HomepageContent, error) {
	if mock.GetHomepageContentFunc == nil {
		panic("ClienterMock.GetHomepageContentFunc: method is nil but Clienter.GetHomepageContent was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		Path:         path,
	}
	mock.lockGetHomepageContent.Lock()
	mock.calls.GetHomepageContent = append(mock.calls.GetHomepageContent, callInfo)
	mock.lockGetHomepageContent.Unlock()
	return mock.GetHomepageContentFunc(ctx, authToken, collectionID, lang, path)
}

// GetHomepageContentCalls gets all the calls that were made to GetHomepageContent.
// Check the length with:
//
//	len(mockedClienter.GetHomepageContentCalls())
func (mock *ClienterMock) GetHomepageContentCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	Path         string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}
	mock.lockGetHomepageContent.RLock()
	calls = mock.calls.GetHomepageContent
	mock.lockGetHomepageContent.RUnlock()
	return calls
}

// GetPageData calls GetPageDataFunc.
func (mock *ClienterMock) GetPageData(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageData, error) {
	if mock.GetPageDataFunc == nil {
		panic("ClienterMock.GetPageDataFunc: method is nil but Clienter.GetPageData was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetPageData.Lock()
	mock.calls.GetPageData = append(mock.calls.GetPageData, callInfo)
	mock.lockGetPageData.Unlock()
	return mock.GetPageDataFunc(ctx, authToken, collectionID, lang, uri)
}

// GetPageDataCalls gets all the calls that were made to GetPageData.
// Check the length with:
//
//	len(mockedClienter.GetPageDataCalls())
func (mock *ClienterMock) GetPageDataCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetPageData.RLock()
	calls = mock.calls.GetPageData
	mock.lockGetPageData.RUnlock()
	return calls
}

// GetPageDescription calls GetPageDescriptionFunc.
func (mock *ClienterMock) GetPageDescription(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageDescription, error) {
	if mock.GetPageDescriptionFunc == nil {
		panic("ClienterMock.GetPageDescriptionFunc: method is nil but Clienter.GetPageDescription was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetPageDescription.Lock()
	mock.calls.GetPageDescription = append(mock.calls.GetPageDescription, callInfo)
	mock.lockGetPageDescription.Unlock()
	return mock.GetPageDescriptionFunc(ctx, authToken, collectionID, lang, uri)
}

// GetPageDescriptionCalls gets all the calls that were made to GetPageDescription.
// Check the length with:
//
//	len(mockedClienter.GetPageDescriptionCalls())
func (mock *ClienterMock) GetPageDescriptionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetPageDescription.RLock()
	calls = mock.calls.GetPageDescription
	mock.lockGetPageDescription.RUnlock()
	return calls
}

// GetPageTitle calls GetPageTitleFunc.
func (mock *ClienterMock) GetPageTitle(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.PageTitle, error) {
	if mock.GetPageTitleFunc == nil {
		panic("ClienterMock.GetPageTitleFunc: method is nil but Clienter.GetPageTitle was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetPageTitle.Lock()
	mock.calls.GetPageTitle = append(mock.calls.GetPageTitle, callInfo)
	mock.lockGetPageTitle.Unlock()
	return mock.GetPageTitleFunc(ctx, authToken, collectionID, lang, uri)
}

// GetPageTitleCalls gets all the calls that were made to GetPageTitle.
// Check the length with:
//
//	len(mockedClienter.GetPageTitleCalls())
func (mock *ClienterMock) GetPageTitleCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetPageTitle.RLock()
	calls = mock.calls.GetPageTitle
	mock.lockGetPageTitle.RUnlock()
	return calls
}

// GetPublishedData calls GetPublishedDataFunc.
func (mock *ClienterMock) GetPublishedData(ctx context.Context, uriString string) ([]byte, error) {
	if mock.GetPublishedDataFunc == nil {
		panic("ClienterMock.GetPublishedDataFunc: method is nil but Clienter.GetPublishedData was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UriString string
	}{
		Ctx:       ctx,
		UriString: uriString,
	}
	mock.lockGetPublishedData.Lock()
	mock.calls.GetPublishedData = append(mock.calls.GetPublishedData, callInfo)
	mock.lockGetPublishedData.Unlock()
	return mock.GetPublishedDataFunc(ctx, uriString)
}

// GetPublishedDataCalls gets all the calls that were made to GetPublishedData.
// Check the length with:
//
//	len(mockedClienter.GetPublishedDataCalls())
func (mock *ClienterMock) GetPublishedDataCalls() []struct {
	Ctx       context.Context
	UriString string
} {
	var calls []struct {
		Ctx       context.Context
		UriString string
	}
	mock.lockGetPublishedData.RLock()
	calls = mock.calls.GetPublishedData
	mock.lockGetPublishedData.RUnlock()
	return calls
}

// GetPublishedIndex calls GetPublishedIndexFunc.
func (mock *ClienterMock) GetPublishedIndex(ctx context.Context, params *zebedee.PublishedIndexRequestParams) (zebedee.PublishedIndex, error) {
	if mock.GetPublishedIndexFunc == nil {
		panic("ClienterMock.GetPublishedIndexFunc: method is nil but Clienter.GetPublishedIndex was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *zebedee.PublishedIndexRequestParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockGetPublishedIndex.Lock()
	mock.calls.GetPublishedIndex = append(mock.calls.GetPublishedIndex, callInfo)
	mock.lockGetPublishedIndex.Unlock()
	return mock.GetPublishedIndexFunc(ctx, params)
}

// GetPublishedIndexCalls gets all the calls that were made to GetPublishedIndex.
// Check the length with:
//
//	len(mockedClienter.GetPublishedIndexCalls())
func (mock *ClienterMock) GetPublishedIndexCalls() []struct {
	Ctx    context.Context
	Params *zebedee.PublishedIndexRequestParams
} {
	var calls []struct {
		Ctx    context.Context
		Params *zebedee.PublishedIndexRequestParams
	}
	mock.lockGetPublishedIndex.RLock()
	calls = mock.calls.GetPublishedIndex
	mock.lockGetPublishedIndex.RUnlock()
	return calls
}

// GetRelease calls GetReleaseFunc.
func (mock *ClienterMock) GetRelease(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.Release, error) {
	if mock.GetReleaseFunc == nil {
		panic("ClienterMock.GetReleaseFunc: method is nil but Clienter.GetRelease was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetRelease.Lock()
	mock.calls.GetRelease = append(mock.calls.GetRelease, callInfo)
	mock.lockGetRelease.Unlock()
	return mock.GetReleaseFunc(ctx, authToken, collectionID, lang, uri)
}

// GetReleaseCalls gets all the calls that were made to GetRelease.
// Check the length with:
//
//	len(mockedClienter.GetReleaseCalls())
func (mock *ClienterMock) GetReleaseCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetRelease.RLock()
	calls = mock.calls.GetRelease
	mock.lockGetRelease.RUnlock()
	return calls
}

// GetResourceBody calls GetResourceBodyFunc.
func (mock *ClienterMock) GetResourceBody(ctx context.Context, authToken string, collectionID string, lang string, uri string) ([]byte, error) {
	if mock.GetResourceBodyFunc == nil {
		panic("ClienterMock.GetResourceBodyFunc: method is nil but Clienter.GetResourceBody was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetResourceBody.Lock()
	mock.calls.GetResourceBody = append(mock.calls.GetResourceBody, callInfo)
	mock.lockGetResourceBody.Unlock()
	return mock.GetResourceBodyFunc(ctx, authToken, collectionID, lang, uri)
}

// GetResourceBodyCalls gets all the calls that were made to GetResourceBody.
// Check the length with:
//
//	len(mockedClienter.GetResourceBodyCalls())
func (mock *ClienterMock) GetResourceBodyCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetResourceBody.RLock()
	calls = mock.calls.GetResourceBody
	mock.lockGetResourceBody.RUnlock()
	return calls
}

// GetResourceStream calls GetResourceStreamFunc.
func (mock *ClienterMock) GetResourceStream(ctx context.Context, authToken string, collectionID string, lang string, uri string) (io.ReadCloser, error) {
	if mock.GetResourceStreamFunc == nil {
		panic("ClienterMock.GetResourceStreamFunc: method is nil but Clienter.GetResourceStream was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetResourceStream.Lock()
	mock.calls.GetResourceStream = append(mock.calls.GetResourceStream, callInfo)
	mock.lockGetResourceStream.Unlock()
	return mock.GetResourceStreamFunc(ctx, authToken, collectionID, lang, uri)
}

// GetResourceStreamCalls gets all the calls that were made to GetResourceStream.
// Check the length with:
//
//	len(mockedClienter.GetResourceStreamCalls())
func (mock *ClienterMock) GetResourceStreamCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetResourceStream.RLock()
	calls = mock.calls.GetResourceStream
	mock.lockGetResourceStream.RUnlock()
	return calls
}

// GetTimeseriesMainFigure calls GetTimeseriesMainFigureFunc.
func (mock *ClienterMock) GetTimeseriesMainFigure(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.TimeseriesMainFigure, error) {
	if mock.GetTimeseriesMainFigureFunc == nil {
		panic("ClienterMock.GetTimeseriesMainFigureFunc: method is nil but Clienter.GetTimeseriesMainFigure was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetTimeseriesMainFigure.Lock()
	mock.calls.GetTimeseriesMainFigure = append(mock.calls.GetTimeseriesMainFigure, callInfo)
	mock.lockGetTimeseriesMainFigure.Unlock()
	return mock.GetTimeseriesMainFigureFunc(ctx, authToken, collectionID, lang, uri)
}

// GetTimeseriesMainFigureCalls gets all the calls that were made to GetTimeseriesMainFigure.
// Check the length with:
//
//	len(mockedClienter.GetTimeseriesMainFigureCalls())
func (mock *ClienterMock) GetTimeseriesMainFigureCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetTimeseriesMainFigure.RLock()
	calls = mock.calls.GetTimeseriesMainFigure
	mock.lockGetTimeseriesMainFigure.RUnlock()
	return calls
}

// GetWithHeaders calls GetWithHeadersFunc.
func (mock *ClienterMock) GetWithHeaders(ctx context.Context, authToken string, path string) ([]byte, http.Header, error) {
	if mock.GetWithHeadersFunc == nil {
		panic("ClienterMock.GetWithHeadersFunc: method is nil but Clienter.GetWithHeaders was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AuthToken string
		Path      string
	}{
		Ctx:       ctx,
		AuthToken: authToken,
		Path:      path,
	}
	mock.lockGetWithHeaders.Lock()
	mock.calls.GetWithHeaders = append(mock.calls.GetWithHeaders, callInfo)
	mock.lockGetWithHeaders.Unlock()
	return mock.GetWithHeadersFunc(ctx, authToken, path)
}

// GetWithHeadersCalls gets all the calls that were made to GetWithHeaders.
// Check the length with:
//
//	len(mockedClienter.GetWithHeadersCalls())
func (mock *ClienterMock) GetWithHeadersCalls() []struct {
	Ctx       context.Context
	AuthToken string
	Path      string
} {
	var calls []struct {
		Ctx       context.Context
		AuthToken string
		Path      string
	}
	mock.lockGetWithHeaders.RLock()
	calls = mock.calls.GetWithHeaders
	mock.lockGetWithHeaders.RUnlock()
	return calls
}

// Post calls PostFunc.
func (mock *ClienterMock) Post(ctx context.Context, authToken string, path string, payload []byte) ([]byte, http.Header, error) {
	if mock.PostFunc == nil {
		panic("ClienterMock.PostFunc: method is nil but Clienter.Post was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AuthToken string
		Path      string
		Payload   []byte
	}{
		Ctx:       ctx,
		AuthToken: authToken,
		Path:      path,
		Payload:   payload,
	}
	mock.lockPost.Lock()
	mock.calls.Post = append(mock.calls.Post, callInfo)
	mock.lockPost.Unlock()
	return mock.PostFunc(ctx, authToken, path, payload)
}

// PostCalls gets all the calls that were made to Post.
// Check the length with:
//
//	len(mockedClienter.PostCalls())
func (mock *ClienterMock) PostCalls() []struct {
	Ctx       context.Context
	AuthToken string
	Path      string
	Payload   []byte
} {
	var calls []struct {
		Ctx       context.Context
		AuthToken string
		Path      string
		Payload   []byte
	}
	mock.lockPost.RLock()
	calls = mock.calls.Post
	mock.lockPost.RUnlock()
	return calls
}

// PublishCollection calls PublishCollectionFunc.
func (mock *ClienterMock) PublishCollection(ctx context.Context, authToken string, collectionID string) error {
	if mock.PublishCollectionFunc == nil {
		panic("ClienterMock.PublishCollectionFunc: method is nil but Clienter.PublishCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
	}
	mock.lockPublishCollection.Lock()
	mock.calls.PublishCollection = append(mock.calls.PublishCollection, callInfo)
	mock.lockPublishCollection.Unlock()
	return mock.PublishCollectionFunc(ctx, authToken, collectionID)
}

// PublishCollectionCalls gets all the calls that were made to PublishCollection.
// Check the length with:
//
//	len(mockedClienter.PublishCollectionCalls())
func (mock *ClienterMock) PublishCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}
	mock.lockPublishCollection.RLock()
	calls = mock.calls.PublishCollection
	mock.lockPublishCollection.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *ClienterMock) Put(ctx context.Context, authToken string, path string, payload []byte) (*http.Response, error) {
	if mock.PutFunc == nil {
		panic("ClienterMock.PutFunc: method is nil but Clienter.Put was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AuthToken string
		Path      string
		Payload   []byte
	}{
		Ctx:       ctx,
		AuthToken: authToken,
		Path:      path,
		Payload:   payload,
	}
	mock.lockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	mock.lockPut.Unlock()
	return mock.PutFunc(ctx, authToken, path, payload)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//
//	len(mockedClienter.PutCalls())
func (mock *ClienterMock) PutCalls() []struct {
	Ctx       context.Context
	AuthToken string
	Path      string
	Payload   []byte
} {
	var calls []struct {
		Ctx       context.Context
		AuthToken string
		Path      string
		Payload   []byte
	}
	mock.lockPut.RLock()
	calls = mock.calls.Put
	mock.lockPut.RUnlock()
	return calls
}

// PutDatasetInCollection calls PutDatasetInCollectionFunc.
func (mock *ClienterMock) PutDatasetInCollection(ctx context.Context, authToken string, collectionID string, lang string, datasetID string, state string) error {
	if mock.PutDatasetInCollectionFunc == nil {
		panic("ClienterMock.PutDatasetInCollectionFunc: method is nil but Clienter.PutDatasetInCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		DatasetID    string
		State        string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		DatasetID:    datasetID,
		State:        state,
	}
	mock.lockPutDatasetInCollection.Lock()
	mock.calls.PutDatasetInCollection = append(mock.calls.PutDatasetInCollection, callInfo)
	mock.lockPutDatasetInCollection.Unlock()
	return mock.PutDatasetInCollectionFunc(ctx, authToken, collectionID, lang, datasetID, state)
}

// PutDatasetInCollectionCalls gets all the calls that were made to PutDatasetInCollection.
// Check the length with:
//
//	len(mockedClienter.PutDatasetInCollectionCalls())
func (mock *ClienterMock) PutDatasetInCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	DatasetID    string
	State        string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		DatasetID    string
		State        string
	}
	mock.lockPutDatasetInCollection.RLock()
	calls = mock.calls.PutDatasetInCollection
	mock.lockPutDatasetInCollection.RUnlock()
	return calls
}

// PutDatasetVersionInCollection calls PutDatasetVersionInCollectionFunc.
func (mock *ClienterMock) PutDatasetVersionInCollection(ctx context.Context, authToken string, collectionID string, lang string, datasetID string, edition string, version string, state string) error {
	if mock.PutDatasetVersionInCollectionFunc == nil {
		panic("ClienterMock.PutDatasetVersionInCollectionFunc: method is nil but Clienter.PutDatasetVersionInCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		DatasetID    string
		Edition      string
		Version      string
		State        string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		DatasetID:    datasetID,
		Edition:      edition,
		Version:      version,
		State:        state,
	}
	mock.lockPutDatasetVersionInCollection.Lock()
	mock.calls.PutDatasetVersionInCollection = append(mock.calls.PutDatasetVersionInCollection, callInfo)
	mock.lockPutDatasetVersionInCollection.Unlock()
	return mock.PutDatasetVersionInCollectionFunc(ctx, authToken, collectionID, lang, datasetID, edition, version, state)
}

// PutDatasetVersionInCollectionCalls gets all the calls that were made to PutDatasetVersionInCollection.
// Check the length with:
//
//	len(mockedClienter.PutDatasetVersionInCollectionCalls())
func (mock *ClienterMock) PutDatasetVersionInCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	DatasetID    string
	Edition      string
	Version      string
	State        string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		DatasetID    string
		Edition      string
		Version      string
		State        string
	}
	mock.lockPutDatasetVersionInCollection.RLock()
	calls = mock.calls.PutDatasetVersionInCollection
	mock.lockPutDatasetVersionInCollection.RUnlock()
	return calls
}

// SaveContentToCollection calls SaveContentToCollectionFunc.
func (mock *ClienterMock) SaveContentToCollection(ctx context.Context, authToken string, collectionID string, pagePath string, content interface{}) error {
	if mock.SaveContentToCollectionFunc == nil {
		panic("ClienterMock.SaveContentToCollectionFunc: method is nil but Clienter.SaveContentToCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		PagePath     string
		Content      interface{}
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		PagePath:     pagePath,
		Content:      content,
	}
	mock.lockSaveContentToCollection.Lock()
	mock.calls.SaveContentToCollection = append(mock.calls.SaveContentToCollection, callInfo)
	mock.lockSaveContentToCollection.Unlock()
	return mock.SaveContentToCollectionFunc(ctx, authToken, collectionID, pagePath, content)
}

// SaveContentToCollectionCalls gets all the calls that were made to SaveContentToCollection.
// Check the length with:
//
//	len(mockedClienter.SaveContentToCollectionCalls())
func (mock *ClienterMock) SaveContentToCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	PagePath     string
	Content      interface{}
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		PagePath     string
		Content      interface{}
	}
	mock.lockSaveContentToCollection.RLock()
	calls = mock.calls.SaveContentToCollection
	mock.lockSaveContentToCollection.RUnlock()
	return calls
}
