---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15

inputs:
  - name: dp-api-clients-go
    path: dp-api-clients-go

run:
  path: dp-api-clients-go/ci/scripts/build.sh
